### ISSUE TITLE
Need way to convert secrets into non-secrets by mutual agreement

### ISSUE THREAD

**Issue by jeremy-w** [kemitchell/switchmode#14]
If I missed this, my apologies. :)

In particular, I'd want to push most every company I work for to allow me to disclose that I worked for them. Being able to say "we work with this impressive list of well-known companies", even if you can't say what you did for them, helps in marketing.

If you can also talk about what you did as a case study in a profile, so much the better.

(Plus, if you can be more open, it gets so much easier to write a résumé.)

**Comment by kemitchell** [comment]
This has been on my mind.

In my experience, this leeway is not terribly hard to get ... after the fact ... when things have gone well. It is _very_ difficult to get from large and even smaller companies in the contract, as an explicit permission or (God forbid) a trademark license.

It is very common to have some kind of "written permission" mechanism as an exception to confidentiality requirements. You promise not to divulge confidences, unless they tell you that you can. It takes some thought to do that right ... notably around who can give permission, how they give permission, and records of the message that all can refer to later, if there's a disconnect.

**Comment by kemitchell** [comment]
There's a bit of legal subtext here that doesn't quite go without saying.

It's possible to give what lawyers call a _waiver_ --- essentially, a free pass to the other side for violating the terms of an agreement in a specific way. For example, a waiver of the NDA obligation to keep the fact of a client-contractor relationship secret. The important part is to make sure there's good evidence of the waiver---usually written---and the fact that it came from someone with legal authority to give it on behalf of the client/company---usually an executive officer. Whenever there's anything serious at stake, it's worth talking to a lawyer about what's needed to paper a waiver reliably.

In general, I try to avoid writing out rules from the background law in contracts, for two reasons:

1. Since the rules apply whether the contract describes them or not, adding them makes contracts longer without saying more.

2. There's always a risk that I'll summarize the rule in some way incorrectly. Perhaps because I try to put it short and sweet, without delving into an exception that ends up mattering in a specific relationship. Perhaps because a court will read the summary together with the rest of the contract, affecting its meaning in unanticipated ways.

There's a major exception to this rule: When I expect that my clients will use a form as much as possible without my attention or involvement, it sometimes pays to write a mechanism out, so businessfolks looking over the terms realize they have the possibility, and how to use it.  I can't expect folks who haven't studied law to read all the "defaults" in between the lines, as lawyers would.

Back to bragging about your clientele. I'm leaning _against_ addressing it directly, for a couple of reasons:

1. In my experience, it's very, very hard to get clients to agree to that kind of thing up front, in contract terms. They're not sure if the relationship will be a good one yet.  And giving permission to use the company name and probably logo often triggers a need for review from a different lawyer or business group.

2.  Even when contractors get good written permission to brag about a client by name---as a waiver or even in terms---as a practical matter, it's always subject to client approval. Even if you have permission to use a name and logo under a contract, if the marketing or trademark people at the client protest, you'll probably take it down, as a matter of good client relations, regardless.

**Comment by jeremy-w** [comment]
All good points. The point about not summarizing defaults makes a lot of sense - effectively, that ability already exists via the system this is implemented in, without need for any additional language. Thanks!
