### ISSUE TITLE
Techie: Unclear language around advance payment for expenses

### ISSUE THREAD

**Issue by jeremy-w** [kemitchell/switchmode#4]
I couldn't sort out what this meant in practice:

> _Company_ agrees to advance _Developer_ expenses likely to exceed _Project_ fees for the month incurred, on written request.

Specifically, "advancing expenses" confused me - it reads like "you lose the money even sooner" because the expenses are, well, advanced. Maybe the intent was to advance reimbursement for expenses into an extraordinary immediate payment vs rolling in with the monthly bill dev sends to co?

Further confusing this was "exceed Project fees" - aren't reasonable expenses billed as _part_ of Project fees, and so could never exceed the total they're a subterm of?

**Comment by kemitchell** [comment]
Yes, this could be much clearer.

You also caught on to the intended meaning: Company puts money in Developer's hand _before_ Developer incurs the expense, as opposed to Developer comes out of pocket, bills the expense, and waits for Company to pay the bill.

I'll come up with substitute language in a few minutes, and post it here. Would _really_ appreciate your thoughts on it.

**Comment by kemitchell** [comment]
@jeremy-w, does this read any better?

> On Notice of an expense that will likely cost more than Project fees in the same month, Company agrees to pay the expense directly, on Developer's behalf, or to request and pay a separate bill for the expense. Company agrees to pay Developer all correctly billed expenses of this kind within [seven calendar days] of receiving each bill.

As usual, the process of cleaning up bad language led to realizations about the meaning, too. This new language adds two new elements:

1. Company can pay the expense for Developer, instead of paying Developer. In practice, I suspect larger companies will prefer to set up one payment process, for paying Developer, and avoid paying directly, while smaller companies will prefer to pay directly, say with a credit card.

2. It's now clear that Developer will _bill_ the extraordinary expense. This is best practice, for one. And it connects this provision to the general terms about late payment, including the ability to stop work when not paid on time.

The payment deadline for expenses needs to be shorter, since in most cases Developer will need whatever it is that needs to be bought to make progress. That means another fill-in-the-blank value. But that's not so bad.

**Comment by jeremy-w** [comment]
That is clearer, but it raises a few questions:

- Does this guarantee billing per best practice in all cases? With the new language, Dev only has to bill Company if they choose the "pay the Dev" option rather than the "pay directly" option, right? If the intent is to always bill per best practice, I don't know this accomplishes that.

- What about projects billing per a schedule in Project Summary that isn't tied to the calendar month? Maybe this should be something like "greater than the amount expected to be billed and paid within the next 30 calendar days".

- Predicting the future: With the monthly hourly bill approach and free work terms, it might be hard to predict the amount the next bill will be for. Basing this on the last bill paid after the trip was agreed would be cleaner. That would leave any trips at short or medium notice in the lurch, though, so might lead to advance payment fairly often. (Which might not be a bad thing.)

- When exactly is within X calendar days: Since late payment opens up stop work, I'm leery of an off by one error here. There are also issues with time zones (say, Pacific Time billing Indian Standard Time with an 11.5 hour difference) - whose day wins? Especially if the clock falls back. Doing it in terms of hours from bill dispatch as a countdown clock, without regard for calendar days, would be weird but also precise and clear. (I'm pretty sure this mostly "developer bitten by date and time bugs" paranoia. In practice, you'd be unlikely to try to slam the gates dead on the end of the grace period.)

**Comment by jeremy-w** [comment]
Maybe useful context:

- I'm used to statements of work saying up front "you'll get billed $X, and you agree to pay up to $Y in travel and expenses". The purchase order is then at least large enough to cover X+Y, but probably more like 1.5*X + Y in order to cover projects running long without need to run back through the PO process.

- I've seen big companies pay for short term, immediate work by credit card because their PO and vendor onboarding process is too slow.

**Comment by kemitchell** [comment]
@jeremy-w, some excellent points and feedback here. I can corroborate the points you drew from your own working experience.

Looking over your points, I see a few themes:

1. The "likely cost more than Project fees in the same month" is fuzzy and potentially tricky to apply, especially with variations in how Project fees accrue, get billed, and get paid.

2. A concern about the specificity of deadlines for payment.

You're right that the "likely to cost more than..." approach is fuzzy. But that's not necessarily a bad thing.

The obvious, sharper alternative is to set a dollar-amount threshold:

> On Notice of an expense that will cost more than [$200]...

"Likely" is gone, and we have a clear dollar amount. But that means another fill-in-the-blank in the form, which Company and Developer may feel the need to negotiate, and which may go out-of-whack if, say, the relationship expands from a relatively small initial project to projects of greater scope and cost.

I would greatly prefer to "bake in" some language that has the effect of scaling the threshold for prepayment of expenses with the amount of money changing hands for the project. There's no escaping negotiation on those figures!

Very open to additional approaches that add clarity and predictability, while giving us that automatic scaling property.

On deadlines, you're right, there's inherent ambiguity about how they're phrased. Especially to the eyes of folks used to dealing with time in seconds (or milliseconds!) since epoch!

Off-by-one does come up. But in practice, there's an easy way to avoid that ambiguity, which is to send things a day earlier than the earliest reasonable interpretation of the contract allows. It's possible to draft terms that offer fine-grained deadline specificity, but writing a date arithmetic vocabulary into a contract tends to involve quite a bit of language that's difficult to parse. Adding that kind of thing would feel very heavy in this form, which in any event I'd prefer to make shorter if at all possible.

**Comment by kemitchell** [comment]
@jeremy-w, I'm going to go ahead and close this with new language like what I've quoted here in the issue. Mostly so I can cut another release/edition for others to start from.

I'm still very interested in finding a better way to handle some of the issues we've identified!

**Comment by jeremy-w** [comment]
I looked again at the contract, and I see now I was mixing up the fees in a month with the bill for those fees. The contract says flat out fees accumulate hourly and get billed monthly. It's non time-based fees that are left to a free schedule with a fallback for end of project. That eliminates most of my concerns.

It does add some new ones, though:

- Should non-time fees (like expenses) default to getting rolled in with the hourly bill for the month, rather than end of project?
- Or at least the language say that they can be billed as such, unless overridden in summary?
- Is that extra variation in when non-time fees are billed desirable?
- Since non-time fees might not go through till end of project, should the trigger maybe be not a single expense > fees, but rather the accumulated unpaid expenses? This to avoid "death by a thousand cuts".
