### ISSUE TITLE
Techie: Unclear language in License to Release

### ISSUE THREAD

**Issue by jeremy-w** [kemitchell/switchmode#6]
> In either case, unless an executive officer gives _Notice_ of permission to attribute the _Approved Release_ to the _Company_ by name, _Developer_ must substitute a statement that _Developer_ sublicenses under the First Draft of the First Edition Switchmode Developer Agreement in place of any usual copyright notice.

The "substitute a statement" and on bit threw me:

- Substitute a statement *for what?* I don't see any thing it's replacing.
- "substitute a statement that …": The "that" clause reads like a restrictive modifier of "statement". Like "a statement sublicensed under this thing", and the statement is being sublicensed. Which doesn't make sense, but leads to a misparse on first reading.

An example of the statement would go a long way.

But I'm guessing this is intended to read something like:

> In either case, unless an executive officer gives _Notice_ of permission to attribute the _Approved Release_ to the _Company_ by name, _Developer_ must replace any usual copyright statement with a statement that _Developer_ sublicenses their released work per the First Draft of the First Edition Switchmode Developer Agreement.

And I think the example would be something like, "Zelda grants you a sublicense to use this contribution under the terms of XXX. The copyright owner has elected to remain anonymous."

**Comment by kemitchell** [comment]
"Replace" is the better word. I'll push a fix shortly.

I'm not sure about "The copyright owner has elected to remain anonymous." One because messing with the copyright notice in the license form is weird enough as it is, and I'd like to keep it to a minimum. Second because mentioning the Switchmode agreement will make clear what's going on, and Switchmode studiously avoids the loaded term "anonymous". Third because there's nothing to stop a Company from coming forward and claiming code originally released anonymously later on.

That being said, messing with the MIT license attribution line is definitely one of the more interesting parts of Switchmode. If anyone has thoughts about it, now or later, I want to hear them, and I want to be open to them. The commit I push will close this issue, but that part of the conversation is by no means closed!

**Comment by jeremy-w** [comment]
"Developer sublicenses under terms of X."

This still seems weird in two ways:

- Missing object of verb: sublicenses what?
- Missing indirect object of verb: to whom?

The (C) Copyright Name Year avoids any need for "what", but the sublicensing language seems to need that.

The rest of the license normally says who gets a license, but again, the "replace Copyright N with N sublicenses" change now seems to need to tie into the rest of the license to say to whom.
--
Jeremy W. Sherman
http://jeremywsherman.com/
